# Generated by Django 2.1.2 on 2018-10-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoing_events',
            name='oevent_info',
            field=models.TextField(default='', max_length=250),
        ),
    ]
