# Generated by Django 2.1.2 on 2018-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0002_ongoing_events_oevent_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='event_info',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='upcoming_events',
            name='uevent_info',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ongoing_events',
            name='oevent_info',
            field=models.TextField(default='', max_length=300),
        ),
    ]
