# Generated by Django 2.1.2 on 2018-10-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0004_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='event',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
