# Generated by Django 2.1.2 on 2018-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0005_auto_20181030_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ongoing_Events',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.DeleteModel(
            name='Upcoming_Events',
        ),
    ]
