# Generated by Django 2.1.2 on 2018-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0006_auto_20181102_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_item', models.TextField(max_length=200)),
            ],
        ),
    ]
