# Generated by Django 2.1.2 on 2018-11-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0009_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About_Post', models.TextField(max_length=500)),
            ],
        ),
    ]
