# Generated by Django 2.1.2 on 2018-11-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0010_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
